version: "3"
services:
  nginx:
    build:
      context: ./.docker/nginx
    volumes:
      - .:/var/www/magento
    network_mode: "host"
  php:
    build:
      context: ./.docker/php
    volumes:
      - .:/var/www/magento
    environment:
      PHP_IDE_CONFIG: serverName=magento
      MAGE_MODE: developer
    network_mode: "host"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: qwerty
    volumes:
      - mysql_data:/var/lib/mysql
    network_mode: "host"
  redis:
    image: redis:5.0
    volumes:
      - redis_data:/data
    network_mode: "host"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.14
    environment:
      discovery.type: single-node
      cluster.name: magento
      xpack.security.enabled: 0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    network_mode: "host"
  rabbitmq:
    image: rabbitmq:3.7
    environment:
      RABBITMQ_DEFAULT_VHOST: magento
      RABBITMQ_DEFAULT_USER: magento
      RABBITMQ_DEFAULT_PASS: qwerty
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    network_mode: "host"
  mailhog:
    image: mailhog/mailhog
    network_mode: "host"
volumes:
  mysql_data:
  redis_data:
  elasticsearch_data:
  rabbitmq_data:
