version: "3"
services:
  nginx:
    build:
      context: ./.docker/img-nginx
      args:
        USER_ID: ${USER_ID:-1000}
        APP_NAME: ${APP_NAME:-magento}
    volumes:
      - ./.docker/etc-mage-2.x/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/magento
    network_mode: "host"
  php:
    build:
      context: ./.docker/img-php-mage-2.2
      args:
        USER_ID: ${USER_ID:-1000}
    volumes:
      - .:/var/www/magento
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=magento}
      MAGE_MODE: developer
    network_mode: "host"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: qwerty
    volumes:
      - mysql_data:/var/lib/mysql
    network_mode: "host"
  redis:
    image: redis:5.0
    volumes:
      - redis_data:/data
    network_mode: "host"
  mailhog:
    image: mailhog/mailhog
    network_mode: "host"
volumes:
  mysql_data:
  redis_data:
