version: "3.7"
services:
  varnish:
    build:
      context: ./.docker/img-varnish
      dockerfile: varnish.dockerfile
    volumes:
      - ./.docker/etc-magento/varnish.vcl:/etc/varnish/default.vcl:ro
      - varnish_data:/var/lib/varnish
    network_mode: "host"
    hostname: mage-varnish
  nginx:
    image: nginx:stable
    volumes:
      - ./.docker/etc-magento/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${MAGENTO_ROOT_DIR:-.}:/srv/magento:ro
      - ${MAGENTO_MEDIA_DIR:-./pub/media}:/srv/magento/pub/media:ro
    network_mode: "host"
    hostname: mage-nginx
  php:
    build:
      context: ./.docker/img-php-magento
      dockerfile: php.dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-7.2}
        USER_ID: ${USER_ID:-1000}
        USER_NAME: ${USER_NAME:-magento}
    volumes:
      - ${COMPOSER_HOME:-~/.config/composer}:/home/magento/.composer
      - ${COMPOSER_CACHE_DIR:-~/.cache/composer}:/home/magento/.composer/cache
      - ${MAGENTO_ROOT_DIR:-.}:/srv/magento
      - ${MAGENTO_MEDIA_DIR:-./pub/media}:/srv/magento/pub/media
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=magento}
      MAGE_MODE: developer
    network_mode: "host"
    hostname: mage-php
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - mysql_data:/var/lib/mysql
    network_mode: "host"
    hostname: mage-mysql
  redis:
    image: redis:5.0
    volumes:
      - redis_data:/data
    network_mode: "host"
    hostname: mage-redis
  elasticsearch:
    build:
      context: ./.docker/img-elasticsearch
      dockerfile: elasticsearch-6.8.dockerfile
    environment:
      discovery.type: single-node
      cluster.name: magento
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    network_mode: "host"
    hostname: mage-elasticsearch
  rabbitmq:
    image: rabbitmq:3.7-management
    environment:
      RABBITMQ_DEFAULT_VHOST: magento
      RABBITMQ_DEFAULT_USER: magento
      RABBITMQ_DEFAULT_PASS: magento
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    network_mode: "host"
    hostname: mage-rabbitmq
  mailhog:
    image: mailhog/mailhog
    network_mode: "host"
    hostname: mage-mailhog
volumes:
  varnish_data:
  mysql_data:
  redis_data:
  elasticsearch_data:
  rabbitmq_data:
