version: "3.7"
services:
  nginx:
    build:
      context: ./.docker/img-nginx
      args:
        USER_ID: ${USER_ID:-1000}
        APP_NAME: ${APP_NAME:-magento}
    volumes:
      - ./.docker/etc-hs-mage-1.x/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${ROOT_DIR:-.}:/var/www/magento
      - ${MEDIA_DIR:-./media}:/var/www/magento/pub/media
    network_mode: "host"
  php:
    build:
      context: ./.docker/img-hs-php-mage-1.x
      args:
        USER_ID: ${USER_ID:-1000}
    volumes:
      - ${ROOT_DIR:-.}:/var/www/magento
      - ${MEDIA_DIR:-./media}:/var/www/magento/pub/media
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=magento}
    network_mode: "host"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: qwerty
    volumes:
      - mysqldata:/var/lib/mysql
      - ./.docker/etc-hs-mage-1.x/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    network_mode: "host"
  redis:
    image: redis:5.0
    volumes:
      - redisdata:/data
    network_mode: "host"
  mailhog:
    image: mailhog/mailhog
    network_mode: "host"
volumes:
  mysqldata:
  redisdata:
