version: "3.7"
services:
  varnish:
    build:
      context: ./.docker/img-varnish
      dockerfile: varnish.dockerfile
    volumes:
      - ./.docker/etc-mage-2.x/varnish.vcl:/etc/varnish/default.vcl:ro
      - varnish_data:/var/lib/varnish
    network_mode: "host"
  nginx:
    build:
      context: ./.docker/img-nginx
      dockerfile: nginx.dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        APP_NAME: ${APP_NAME:-magento}
    volumes:
      - ./.docker/etc-mage-2.x/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${ROOT_DIR:-.}:/var/www/magento
      - ${MEDIA_DIR:-./pub/media}:/var/www/magento/pub/media
    network_mode: "host"
  php:
    build:
      context: ./.docker/img-php-mage
      dockerfile: mage-2.3.dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    volumes:
      - ${ROOT_DIR:-.}:/var/www/magento
      - ${MEDIA_DIR:-./pub/media}:/var/www/magento/pub/media
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=magento}
      MAGE_MODE: developer
    network_mode: "host"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: qwerty
    volumes:
      - mysql_data:/var/lib/mysql
    network_mode: "host"
  redis:
    image: redis:5.0
    volumes:
      - redis_data:/data
    network_mode: "host"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    environment:
      discovery.type: single-node
      cluster.name: magento
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    network_mode: "host"
  rabbitmq:
    image: rabbitmq:3.7
    environment:
      RABBITMQ_DEFAULT_VHOST: magento
      RABBITMQ_DEFAULT_USER: magento
      RABBITMQ_DEFAULT_PASS: qwerty
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    network_mode: "host"
  mailhog:
    image: mailhog/mailhog
    network_mode: "host"
volumes:
  varnish_data:
  mysql_data:
  redis_data:
  elasticsearch_data:
  rabbitmq_data:
