version: "3.7"
services:
  varnish:
    build:
      context: ./.docker/img-varnish
      dockerfile: varnish.dockerfile
    volumes:
      - ./.docker/etc-mage-2.x/varnish.vcl:/etc/varnish/default.vcl:ro
      - varnish_data:/var/lib/varnish
    network_mode: "host"
  nginx:
    image: nginx:stable
    volumes:
      - ./.docker/etc-mage-2.x/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${ROOT_DIR:-.}/pub:/var/www/magento/pub:ro
      - ${MEDIA_DIR:-./pub/media}:/var/www/magento/pub/media:ro
    network_mode: "host"
  php:
    build:
      context: ./.docker/img-php-mage
      dockerfile: mage-2.2.dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    volumes:
      - ${ROOT_DIR:-.}:/var/www/magento
      - ${MEDIA_DIR:-./pub/media}:/var/www/magento/pub/media
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=magento}
      MAGE_MODE: developer
    network_mode: "host"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - mysql_data:/var/lib/mysql
    network_mode: "host"
  redis:
    image: redis:3.2
    volumes:
      - redis_data:/data
    network_mode: "host"
  elasticsearch:
    build:
      context: ./.docker/img-elasticsearch
      dockerfile: es-5.6.dockerfile
    environment:
      discovery.type: single-node
      cluster.name: magento
      xpack.security.enabled: 0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    network_mode: "host"
  mailhog:
    image: mailhog/mailhog
    network_mode: "host"
volumes:
  varnish_data:
  mysql_data:
  redis_data:
  elasticsearch_data:
