version: "3.7"
services:
  varnish:
    labels:
      - "traefik.http.routers.happysocks.entrypoints=http"
      - "traefik.http.routers.happysocks.rule=Host(`happysocks.localhost`)"
  magento:
    build:
      args:
        PHP_VERSION: 7.2
        NODE_VERSION: 8
  elasticsearch:
    build:
      dockerfile: elasticsearch-5.6.dockerfile
    environment:
      xpack.security.enabled: 0
