version: "3.7"
services:
  varnish:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hs.entrypoints=http"
      - "traefik.http.routers.hs.rule=Host(`happysocks.localhost`)"
  magento:
    build:
      args:
        PHP_VERSION: ${PHP_VERSION:-7.2}
  elasticsearch:
    build:
      dockerfile: elasticsearch-5.6.dockerfile
    environment:
      xpack.security.enabled: 0
