version: "3.7"
services:
  php:
    build:
      args:
        PHP_VERSION: ${PHP_VERSION:-7.2}
  elasticsearch:
    build:
      dockerfile: elasticsearch-5.6.dockerfile
    environment:
      xpack.security.enabled: 0
