version: "3.7"
services:
  traefik:
    image: traefik:2.1
    environment:
      TRAEFIK_ACCESSLOG: "true"
      TRAEFIK_API: "true"
      TRAEFIK_API_INSECURE: "true"
      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: ":80"
      TRAEFIK_ENTRYPOINTS_MYSQL_ADDRESS: ":3306"
      TRAEFIK_ENTRYPOINTS_REDIS_ADDRESS: ":6379"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`localhost`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - 80:80
      - 3306:3306
      - 6379:6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: magento-traefik
  varnish:
    image: varnish:6.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.magento.entrypoints=http"
      - "traefik.http.routers.magento.rule=Host(`magento.localhost`)"
    volumes:
      - ./.docker/etc-magento/varnish.vcl:/etc/varnish/default.vcl:ro
      - varnish-data:/var/lib/varnish
    hostname: magento-varnish
  nginx:
    image: nginx:stable
    volumes:
      - ./.docker/etc-magento/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${MAGENTO_ROOT_DIR:-.}:/srv/magento:ro
      - ${MAGENTO_MEDIA_DIR:-./pub/media}:/srv/magento/pub/media:ro
    hostname: magento-nginx
  magento:
    build:
      context: ./.docker/img-magento
      dockerfile: magento.dockerfile
      args:
        PHP_VERSION: 7.3
        NODE_VERSION: 12
        USER_ID: ${USER_ID:-1000}
    environment:
      PHP_IDE_CONFIG: serverName=magento
      MAGE_MODE: developer
    volumes:
      - ${COMPOSER_HOME:-~/.config/composer}:/home/magento/.composer
      - ${COMPOSER_CACHE_DIR:-~/.cache/composer}:/home/magento/.composer/cache
      - ${MAGENTO_ROOT_DIR:-.}:/srv/magento
      - ${MAGENTO_MEDIA_DIR:-./pub/media}:/srv/magento/pub/media
    hostname: magento
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.mysql.entrypoints=mysql"
      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
    volumes:
      - ./.docker/etc-magento/mysql.cnf:/etc/mysql/conf.d/magento.cnf:ro
      - mysql-data:/var/lib/mysql
    hostname: magento-mysql
  redis:
    image: redis:5.0
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
    volumes:
      - redis-data:/data
    hostname: magento-redis
  elasticsearch:
    build:
      context: ./.docker/img-elasticsearch
      dockerfile: elasticsearch-6.8.dockerfile
    environment:
      discovery.type: single-node
      cluster.name: magento
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    hostname: magento-elasticsearch
  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_VHOST: magento
      RABBITMQ_DEFAULT_USER: magento
      RABBITMQ_DEFAULT_PASS: magento
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.entrypoints=http"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.localhost`)"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    hostname: magento-rabbitmq
  mailhog:
    image: mailhog/mailhog
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.localhost`)"
      - "traefik.http.routers.mailhog.entrypoints=http"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
    hostname: magento-mailhog
volumes:
  varnish-data:
  mysql-data:
  redis-data:
  elasticsearch-data:
  rabbitmq-data:
