providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
entryPoints:
  traefik:
    address: ":8080"
  http:
    address: ":80"
  mysql:
    address: ":3306"
  redis:
    address: ":6379"
api:
  dashboard: true
  insecure: true
accessLog: {}
